export const generateOtp = () => {
    // Generate a random 6-digit OTP
    // The OTP is a string of 6 digits
    // It is generated by creating a random number between 100000 and 999999]
    // and converting it to a string
    // This ensures that the OTP is always 6 digits long
    const otp = Math.floor(Math.random() * 900000) + 100000;
    return otp.toString();
};

